run:
  tests: true

linters:
  enable:
    # High-signal core
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - gosimple
    - unused
    # Style/hygiene
    - revive
    - misspell
    - nolintlint
    # Security (practical subset)
    - gosec
    # Tests
    - thelper
    - tparallel
  settings:
    misspell:
      locale: US
      ignore-words:
        - pokebedrock
        - dragonfly
        - gophertunnel
        - raknet
    gosec:
      includes: [G101, G401]
      excludes: [G204]

issues:
  exclude-use-default: true
  exclude-dirs:
    - vendor
    - docs
    - resources
