run:
  timeout: 5m
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/smell-of-curry/pokebedrock-hub)
linters:
  enable:
    - gci
    - gofmt
  disable-all: true
