[PokeBedrock]
SentryDsn = '' # DSN for Sentry.
LogLevel = 'debug' # Log level.
ServerPath = 'resources/servers' # Path to the servers folder.
SlapperPath = 'resources/slapper' # Path to the slapper folder.
LocalePath = 'resources/locales' # Path to the locales folder.
AFKTimeout = "10m" # The duration for a player to be considered afk.

[Network]
Address = ':19132' # Address to bind to.

[Server]
Name = '§r§cPoke§r§bBedrock§r' # Name of the server.
AuthEnabled = true # Whether authentication is enabled.
DisableJoinQuitMessages = true # Whether join/quit messages are disabled.

[World]
SaveData = true # Whether to save the world data.
Folder = 'resources/world' # Path to the world folder.

[Players]
MaxCount = 50 # Maximum number of players.
MaximumChunkRadius = 16 # Maximum chunk radius.
SaveData = false # Whether to save the player data.
Folder = 'resources/player_data' # Path to the player data folder.

[Resources]
AutoBuildPack = false # Whether to automatically build the resource pack.
Folder = 'resources/resource_pack' # Path to the resource pack folder.
Required = true # Whether the resource pack is required.

[Service]
GinAddress = ':8080' # Address to bind the gin api to.
GinAuthenticationKey = 'secret-key' # Key for the authentication API.
RolesURL = 'http://localhost:4000' # URL to the roles API.
ModerationUrl = 'https://pokebedrock.com/api/moderation' # URL to the moderation API.
ModerationKey = 'xxxxxx-xxxxx-xxxxxx-xxxxx' # Key for the moderation API.
VpnURL = 'http://ip-api.com/json' # URL to the VPN API.

[RestartManager]
MaxWaitTime = "10m" # Maximum time a server will wait before force restart.
BackoffInterval = "3m" # Backoff interval between retries.
RestartCooldown = "5m" # Minimum time between restarts for the same server.
QueueTimeout = "30m" # Time after which queue entries expire.
